name: flutter_custom_payments
description: A Package intended to manage multiple payment methods
version: 0.0.1
homepage: null

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_credit_card: ^3.0.4
  flutter_slidable: ^2.0.0
  flutter_stripe: ^5.1.0
  flutter_work_utils: ^0.0.2
  http: ^0.13.5
  http_request_utils: ^0.2.6
  page_transition: ^2.0.9
  provider: ^6.0.4
  skeletons: ^0.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/no-image.png
    - assets/brands/visa_logo.png
    - assets/brands/mastercard_logo.jpeg
flutter_intl:
  enabled: true
  class_name: FP